version: '3.0'
services:
  frontend:
    build: frontend
    volumes:
      - ./frontend:/app:delegated
    ports:
      - 3001:3001
  backend:
    build: backend
    volumes:
      - ./backend:/app:delegated
    ports:
      - 3000:3000
  redis:
    image: redis:alpine
    ports:
      - 6379:6379